apiVersion: v1
kind: Pod
metadata:
  name: eos-all-hostpath
spec:
  containers:
  - name: idle
    image: gitlab-registry.cern.ch/linuxsupport/alma9-base:latest
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
    volumeMounts:
    - name: eos
      mountPath: /eos
      mountPropagation: HostToContainer
  volumes:
  - name: eos
    hostPath:
      path: /var/eos
